### PR TITLE
Be more aware of errors in subprocesses

### PR DESCRIPTION
**Pull request by ghanneman**
Hi Moses developers!

Here's a small change to make the extract-parallel Perl script a little better at error catching.  I noticed that the subprocesses could sometimes die (e.g. run out of disk space in sorting), but the main script would continue.  That led to some incomplete phrase tables and bad gzip files.  Hope it looks all right to you!

### CODE REVIEW

**Comment by hieuhoang** [comment]
great! Thank you very much

**Comment by hieuhoang** [comment]
When I run the regression tests, it fails for the tests
 misc.extract-parallel
 misc.extract-parallel-weighted
With errors
  ...
   sh: 1: set: Illegal option -o pipefail
   sh: 1: set: Illegal option -o pipefail
   ...
I've reverted the commit. 
   https://github.com/moses-smt/mosesdecoder/commit/1fca3f8a7527bb10c76117e67c6fec929e96d539
We can reapply it once we figure out what the issue is

**Comment by ugermann** [comment]
Ubuntu uses dash by default (sh), not bash. Explicitly specify bash and
things should work.

- Uli

On Tue, Oct 13, 2015 at 1:57 PM, Hieu Hoang <notifications@github.com>
wrote:

> When I run the regression tests, it fails for the tests
> misc.extract-parallel
> misc.extract-parallel-weighted
> With errors
> ...
> sh: 1: set: Illegal option -o pipefail
> sh: 1: set: Illegal option -o pipefail
> ...
> I've reverted the commit.
> 1fca3f8
> <https://github.com/moses-smt/mosesdecoder/commit/1fca3f8a7527bb10c76117e67c6fec929e96d539>
> We can reapply it once we figure out what the issue is
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moses-smt/mosesdecoder/pull/131#issuecomment-147706910>
> .
>



-- 
Ulrich Germann
Senior Researcher
School of Informatics
University of Edinburgh

**Comment by hieuhoang** [comment]
cheers. All is well with the world
    https://github.com/moses-smt/mosesdecoder/commit/d6dda4f292614408d53c4169df73ec31ed981146

**Comment by hieuhoang** [comment]
sorry guys. The change now breaks the cruise control, which runs an end-to-end training pipeline in a cron job. 
      http://www.statmt.org/moses/cruise/
Had to roll back.
   https://github.com/moses-smt/mosesdecoder/commit/384e0b06d298fe308bd39c6c567f9cf93f42e074
Not sure how to proceed. Maybe we don't need the redirect code to /dev/stderr. I'll have a think about it when I have time

**Comment by ghanneman** [comment]
Was it the same pipefail problem from the regression tests that broke Cruise Control?  (From the log, I couldn't actually find any explicit error except the final line reporting "FAIL:ems".)

**Comment by hieuhoang** [comment]
I'm not sure whether it's due to your code, or it had always failed but the
error handling didn't pick it up before.

you can't see it in the log, only when you log onto the (Edin) machine and
look at the error file for that particular step. So not sure how you'll be
able to go about debugging it.

It's likely to be a permissioning problem specific to cronjobs

Hieu Hoang
http://www.hoang.co.uk/hieu

**Comment by ghanneman** [comment]
Ah, got it.  Let me know if you want me to do anything :-)

**Comment by hieuhoang** [comment]
Hey @ghanneman , Jeroen has rewritten score-parallel in python to be more robust. 
   https://github.com/moses-smt/mosesdecoder/commit/710915c088ae8277cfffbbf76e2ecef2e520e93f
is this something you'll be interested in?

**Pull request merged**
