### PR TITLE
Updated hashCode generation at NeuralLMWrapper.cpp

### PR DESCRIPTION
**Pull request by pakozm**
Changed to consider the last n-1 words instead of the whole ngram n words.

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
Hey, it's been a while since I wrote that. Could you please explain why it should be the last n-1 words?

**Comment by pakozm** [comment]
In ngram LMs the state of the model is represented by a sequence of n-1 words, which corresponds with the history used to compute the next word probability distribution. This concerns also to count-based models not only neural-based ones. So, if the LM is given a 3-gram "a b c", it computes P(c|a b), being the current LM state "a b" and the LM state for the next word "b c". Consequently, if the word "d" is received as next word by this LM, the probability computed will be P(d|b c) using "b c" as the current state. Following this reasoning, the decoder should consider as equal LM states which share the same n-1 words history, ignoring any word previous to the n-1.

**Comment by hieuhoang** [comment]
do you have any experimental results, out of interest?

**Comment by pakozm** [comment]
The problem is related with correctness of this particular use of ngram LMs, in case I have understood properly what information is contained in the context factors received at getValue() function. I have understood this function receives a whole ngram which should be evaluated by the LM returning a probability and a destination state of the LM after the transition with this ngram. Please, let me know if this interpretation is correct.

If I'm correct, in this scenario the LM goes from its current state (identified by n-1 words) and applies a transition with word n, arriving to the state defined by the last n-1 words (excluding the first one).

We don't have experiments using this approach in Moses. Our interest is to implement a shrinked version of NPLM which we are willing to connect with Moses, so we need a new NeuralLMWrapper because our version is not back-compatible. Reviewing this code we found it could be potentially wrong, if our interpretation of getValue() method is correct. So, until we have our version finished we won't be able to give you any experimental results on this issue.

Nevertheless, we have work with feedforward NNLMs and ngram LMs during several years in our own decoder with handwritten text and speech recognition and with machine translation. Particularly, we have a tool which transforms ARPA files into a FSM. In order to produce the exact behavior, every FSM state at the highest ngram level is identified with the n-1 words in the history of the LM. The same applies to any other ngram LM, even to Neural ones which we have also used in our decoder.

Finally, regarding decoding translation quality I think it will be very similar after this change. But this issue is more related with correctness than an empirical one. However, it should affect the number of states generated by the decoder in every LM evaluation.

Let me know if you consider this as important. In any case we will continue working in our shrinked NPLM-like source code, so we will be able to compare both ideas after we finished coding this part. I  apologize by the confusion, but I have opened this pull request because I thought this issue doesn't need empirical evaluation because it is more related with theory than practice use of the model.

**Comment by hieuhoang** [comment]
ok thanks for comment. We'll look into it.

You're quite right, it's not an empirical issue. We just wondering how you came across the bug

**Comment by pakozm** [comment]
Thanks @hieuhoang , I will come back to you when we have experimental results using our NPLM-like implementation. Let me know if you think about this problem and make a decision.
Sincerely

**Comment by hieuhoang** [comment]
i've pulled it into master. Not tested it as I don't know how to train an NNLM, but your fix seems reasonable

**Comment by pakozm** [comment]
Thanks @hieuhoang I will come back with sour benchmarks as soon as we have them done.

**Pull request merged**
