### PR TITLE
Fix some problems in EMS

### PR DESCRIPTION
**Pull request by gumblex**
* remove absolute links
* fix coverage bar highlighting
* change [Base64 library](https://github.com/dankogai/js-base64) to support UTF-8

### CODE REVIEW

**Comment by gumblex** [comment]
By the way, please add in wiki page "Experiment Management System", section "Web Interface" that the executable `biconcor` binary should be copied to the web interface directory to use the bilingual concordancer. Or the user will be confused.

**Comment by hieuhoang** [comment]
Thanks. I don't know enough about these scripts to pull your changes, but if you're sure about it, I can give you commit access for you to do it yourself, as long as you answer bug queries from other users on the moses mailing list. Or if anyone else knows more about it, maybe they can commit it for you.

I've change the wiki as you explained

**Comment by gumblex** [comment]
I think these changes won't cause further complaints, though I will keep an eye on it.
According to the commit history, @phikoehn should know more about this.

**Comment by hieuhoang** [comment]
So you want to push it yourself? I can add you ti the committers list. What's your email address?

**Comment by gumblex** [comment]
abcdoyle888 at gmail.com

**Pull request merged**
