### PR TITLE
Fix the incorrect processing considering fullwidth number character

### PR DESCRIPTION
**Pull request by JetRunner**
The pre-processing script is wrong when processing number "1". It incorrectly substitute "1" with ‘“’. This PR helps fix this error.

### CODE REVIEW

**Comment by hieuhoang** [comment]
I'm not sure I can pull this as I think it's going to mess up the non-Chinese processing. Maybe someone else knows more.

Perhaps you can create a copy of the file with this change just for Chinese

**Comment by JetRunner** [comment]
Hi @hieuhoang ! I realized that I didn't specify the context in my pull request. I should have made it more clear. First, this script is obviously used for converting fullwidth character to halfwidth. This situation often occurs in Chinese and Japanese. You can find a more detailed explanation on Wikipedia https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

image
 As you can see from this image from Wikipedia, the fullwidth character "1" should be substituted to its halfwidth character. I have changed the name of this pull request.

**Comment by hieuhoang** [comment]
Thanks for the explanation. I think this script isn't only to convert full width to hald width character, as you say. It's also to normalizes punctuations in many European text.

Perhaps if you just want to do this character replacement, you can run what you want just before this script, eg
   cat input-text | sed s/１/1/g | ./replace-unicode-punctuation.perl

**Comment by JetRunner** [comment]
I already did. On the other hand, I’m not sure if full width 1 has a special role in European languages as you said (though it’s not likely if you see the originality of full width characters). I guess maybe the original author of the script can help with that. I understand why you are very careful with this PR since it’s a break change.

**Comment by JetRunner** [comment]
According to my experience, nearly all European languages use half width characters. A full width digit 1 essentially cannot appear in a European language.

**Comment by hieuhoang** [comment]
What do you mean by half width and full width? Do you mean utf8 and utf16?

**Comment by hieuhoang** [comment]
I'm going to close this without pulling as it breaks the existing pipeline

It would be good to have a script that normalize cjk text but it would have
to be in a different script

**Comment by JetRunner** [comment]
Yes, you can do that. I’ve forked my own version of Moses. I’m rather disappointed that such simple fix cannot be addressed. Though it is really a bug. Just do some research and read these links please. As I said, this is obviously a bug, caused by a copy from previous line without modifying the substitution.

https://support.microsoft.com/en-us/help/225136/how-to-convert-full-width-numbers-to-half-width-numbers
https://en.m.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

**Comment by JetRunner** [comment]
You are building a machine translation system but you choose not to believe a native speaker and researcher in this field. It that a spirit of science (or engineering)?

**Comment by hieuhoang** [comment]
I believe you but I can't break the existing pipeline.

It's no big deal, make a copy of the script (call it normalize-cjk.perl
etc) and do whatever you want. Will gladly pull them

**Comment by JetRunner** [comment]
But breaks what? Could you show an example here?

**Comment by JetRunner** [comment]
The reason why I submit this PR in the first place is that this repo is used in Facebook’s XLM. This script is used but messes up CJK fullwidth digits. That’s the reason I want to fix it.

**Comment by JetRunner** [comment]
If you have a math lib calculating 1+1=3, should you fix the lib? Or you just create another for calculating 1+1=2 that does not break “the pipeline”?

**Comment by hieuhoang** [comment]
Looking at the script now. I think you're right

**Comment by hieuhoang** [comment]
You're right. Looking at the context of the code and it's clear that it's a bug. Thanks for being persistent and for the pull request

**Pull request merged**
