### PR TITLE
Fix the evaluate method for GLM. GLM should evaluate transopts after

### PR DESCRIPTION
**Pull request by mtresearcher**
initializing the input

### CODE REVIEW

**Comment by hieuhoang** [comment]
thanks. Does this change make a difference?

This feature function was written before the feature function framework was updated so the code looks a bit strange to me

**Comment by hieuhoang** [comment]
ps. i've given you commit access so you can push changes yourself. Have fun

**Comment by mtresearcher** [comment]
yes, it works now. Before, moses failed while loading the phrase-tables.

**Comment by hieuhoang** [comment]
cool. Merged. thx!

**Comment by hieuhoang** [comment]
oh, forgot to tell you the house rules if you wanna commit stuff yourself:
  1. if you commit, please listen to the mailing list for a few weeks in case someone reports an issue with your commit. (some people use github bug reports but the usual way for most moses users is thru the mailing list)
  2. don't commit large data files or binary files. Some people have slow network connections and checking them out can be a pain.
  3. If you change any of the c++ code, please run the regression test
  4. if you pull someone else's changes, the above also applies.

**Comment by mtresearcher** [comment]
got it! 
to be on the safe side .. I won't commit directly and will always issue pull requests from our fork.

**Pull request merged**
