### PR TITLE
tokenizer improvements, faster better sentence splitter

### PR DESCRIPTION
**Pull request by aminorex**
I got back to this for a couple of days.  Ken scanned some output diffs, and I tried to resolve the problems he noticed (as well as items that bothered me).  I added a sentence splitter, which is just plain better than the perl one, and 140x faster, on my servers.  You could pull https://github.com/aminorex/mosesdecoder now.

New options abound.  Important ones:

tokenization:
-r refined tokenization, makes what I consider improvements for MT purposes.
-e is required to escape Moses special characters.
-a is better implemented (like the perl script)

sentence splitting:
-T does sentence splitting only, 
-X does that and also adds <P> marks like the perl script does.

Plans:

- Test/fix the detokenizer
- Use htmlcxx and add destructuring/restructuring functions.  (Intended for HTML translation,
  table handling, transfer casing.)
- Convert to boost ICU unicode regex (remove RE2 dependency)
- Convert glib calls to ICU calls (conversion and classes)
- Implement option to combine splitting with tokenization

I would wager one Monero that invoking -r -e would give a BLEU boost relative to perl.

### CODE REVIEW

**Comment by hieuhoang** [comment]
cheers. Will spin up the comparison in the next coupla days and get back to you

**Comment by hieuhoang** [comment]
what compiler are you using? ON Ubuntu 12.04 with gcc 4.6.4, I get 2 errors
   contrib/c++tokenizer/tokenizer.cpp:1779:40: error: variable-sized object ‘seq’ may not be initialised
   contrib/c++tokenizer/tokenizer.cpp:1780:36: error: variable-sized object ‘pos’ may not be initialised
I have more errors on osx/clang, but will deal with them later

**Comment by aminorex** [comment]
g++ 4.9.1

not errors, but misguided warnings, in this case.  = {0} should fix them.
 i have no ready clang environment, so pasting me the messages would be
helpful.

**Comment by hieuhoang** [comment]
i've made it compile on clang, but only by commenting out the offending code 'cos I wasn't really sure what they do:
   https://github.com/moses-smt/mosesdecoder/commit/d71e516176ee3c828439abb9ec8455300915f651
And just changed arrays to vectors

Could u take a look at where is says
   TODO clang error
and see what u can do. The errors are:
   
contrib/c++tokenizer/tokenizer.cpp:1592:45: error: member reference base type 'value_type' (aka 'char') is not a structure or union
                    lines[ithread][line_pos].clear(); 
                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
contrib/c++tokenizer/tokenizer.cpp:1595:45: error: member reference base type 'value_type' (aka 'char') is not a structure or union
                    lines[ithread][line_pos].clear();
                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
contrib/c++tokenizer/tokenizer.cpp:1597:46: error: assigning to 'value_type' (aka 'char') from incompatible type 'std::__1::basic_string<char>'
                    lines[ithread][line_pos] = 
                                             ^
contrib/c++tokenizer/tokenizer.cpp:1604:35: error: no matching constructor for initialization of 'Tokenizer::VectorTokenizerCallable'
                    boost::thread(VectorTokenizerCallable(this,lines[ithread],results[ithread])); 
                                  ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
contrib/c+

**Comment by aminorex** [comment]
last pull request should be good, deal with these.

**Pull request merged**
