### PR TITLE
Added threads options for filter-model-given-input.pl

### PR DESCRIPTION
**Pull request by alvations**
Added the thread options when binarizing using `processPhraseTableMin` and `processLexicalTableMin`, otherwise the single thread binarization is a bottleneck when we want filter before tuning/testing. 

See latest script at: https://github.com/alvations/mosesdecoder/blob/master/scripts/training/filter-model-given-input.pl

Tested with:

```
MOSES_BIN_DIR=/home/alvas/moses/bin
filter-model-given-input.pl targetdir moses.ini input.text -Binarizer ${MOSES_BIN_DIR}/processPhraseTableMin ${MOSES_BIN_DIR}/processLexicalTableMin -threads 10
```

### CODE REVIEW

**Comment by hieuhoang** [comment]
thanks liling

it's a bit too big for me to pull and for some reason, it can't be merged automatically. 

If you want to push the changes yourself, will be happy to give you commit access. As long as you keep an eye on the mailing list in case bugs are reported in your commits by irate users

**Comment by XapaJIaMnu** [comment]
Do we want to do that?  There have been issues with those phrase tables when using multiple threads during construction?

**Comment by emjotde** [comment]
That should be OK now, I believe I fixed that a while ago. However, 
there is another issue here: The "-encoding None" option should be 
dropped (that was only due to the threading bug), but then pipes cannot 
be used to sort the input as the binarizer does two passes through the 
original file. "-encoding None" can causes more collisions which can 
then be an issue for OSMs and the like.

W dniu 26.04.2015 o 10:15, Nikolay Bogoychev pisze:

**Comment by alvations** [comment]
@XapaJIaMnu , do you mean https://github.com/moses-smt/mosesdecoder/issues/98 ? I've tried and test on quite a large dataset and phrase-table and reordering binarization is the only sane thing to do. 

The filter script with binarizer option only uses a single thread. And before i added the thread option to the filter, i had to do a post-filter multi-threaded binarization and then change the `moses.ini` with some `sed -i`. 

By default, it still uses the single thread. I guess the `-threads` parameters is just users who would want the multi-threaded abilities in the filter script without calling their own commands and then do unorthodox `sed -i`  that `filter-input-given-input.pl` already does.

**Comment by hieuhoang** [comment]
cool. PM'ing you now

**Comment by alvations** [comment]
fixed the merging the dev branch on my repo and moses. Hopefully, it's right.

**Pull request merged**
